# Generated by Django 5.2.17 on 2026-09-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_veiculo_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sistema', 'Sistema')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('finalizada', 'Finalizada'), ('aguardando_humano', 'Aguardando humano')], default='aberta', max_length=30)),
                ('identificador_externo', models.CharField(blank=True, max_length=255)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(choices=[('cliente', 'Cliente'), ('bot', 'Bot'), ('funcionario', 'Funcionário')], max_length=20)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio'), ('documento', 'Documento'), ('outro', 'Outro')], default='texto', max_length=20)),
                ('conteudo', models.TextField(blank=True)),
                ('identificador_externo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('processada_por_ia', models.BooleanField(default=False)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='conversas.conversa')),
            ],
        ),
    ]
