# Generated by Django 5.2.17 on 2026-09-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_veiculo_placa'),
        ('conversas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('revisao', 'Revisão'), ('oleo', 'Óleo e filtros'), ('freios', 'Freios'), ('suspensao', 'Suspensão'), ('direcao', 'Direção'), ('motor', 'Motor'), ('eletrica', 'Elétrica'), ('ar_condicionado', 'Ar-condicionado'), ('orcamento', 'Orçamento'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('relato_cliente', models.TextField(blank=True)),
                ('resumo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('coletando_dados', 'Coletando dados'), ('aguardando_cliente', 'Aguardando cliente'), ('aguardando_oficina', 'Aguardando oficina'), ('agendado', 'Agendado'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='novo', max_length=30)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='normal', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='clientes.cliente')),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='conversas.conversa')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='clientes.veiculo')),
            ],
        ),
    ]
