# Generated by Django 5.2.17 on 2026-09-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='relato_cliente',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='condicoes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='intencao',
            field=models.CharField(choices=[('solicitar_servico', 'Solicitar serviço'), ('solicitar_orcamento', 'Solicitar orçamento'), ('agendar', 'Agendar'), ('consultar_status', 'Consultar status'), ('duvida', 'Dúvida'), ('falar_com_humano', 'Falar com humano'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='sintomas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tempo_problema',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
