# Generated by Django 5.2.17 on 2026-09-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_remove_atendimento_relato_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='trello_card_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='trello_card_url',
            field=models.URLField(blank=True),
        ),
    ]
