# Generated by Django 5.2.17 on 2026-09-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0002_remove_atendimento_relato_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_solicitada', models.DateTimeField(blank=True, null=True)),
                ('data_hora_confirmada', models.DateTimeField(blank=True, null=True)),
                ('periodo_preferido', models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('aguardando_confirmacao', 'Aguardando confirmação'), ('confirmado', 'Confirmado'), ('remarcado', 'Remarcado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='solicitado', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='atendimentos.atendimento')),
            ],
        ),
    ]
