# Generated by Django 5.2.17 on 2026-09-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='data_hora_solicitada',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_solicitada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario_solicitado',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
