# Generated by Django 5.2.17 on 2026-09-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_remove_agendamento_data_hora_solicitada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='observacao_retorno',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('aguardando_confirmacao', 'Aguardando confirmação'), ('confirmado', 'Confirmado'), ('remarcado', 'Remarcado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído'), ('recusado', 'Recusado')], default='solicitado', max_length=30),
        ),
    ]
