# Generated by Django 5.2.17 on 2026-10-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_agendamento_observacao_retorno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='ultimo_status_retorno_gerado',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
