# Generated by Django 5.2.17 on 2026-09-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
